/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zlk.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.zlk.bean.PagerModel;
import com.zlk.business.INewsBusiness;
import com.zlk.pojo.News;
import com.zlk.pojo.Users;
import com.zlk.struts.form.NewsForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-19-2010
 * 
 * XDoclet definition:
 * @struts.action path="/news" name="newsForm" parameter="method" scope="request" validate="true"
 */
public class NewsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
private INewsBusiness newsBusiness;

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
/*	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewsForm newsForm = (NewsForm) form;// TODO Auto-generated method stub
		return null;
	}*/
	
	public ActionForward addNews(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		response.setContentType("text/html;charset=utf-8");
		PrintWriter out = null;
		NewsForm newsForm = (NewsForm) form;// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		newsForm.setAuthor((Users)session.getAttribute("users"));
		boolean flag = newsBusiness.addNews(newsForm);
		try {
			out = response.getWriter();
			if(flag){
				out.println("<script>alert('添加成功');window.location.href='"+request.getContextPath()+"/news.do';</script>");
			}else{
			    out.println("<script>alert('添加失败');window.location.href='"+request.getContextPath()+"/news.do';</script>");
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}                    
	public ActionForward unspecified(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewsForm newsForm = (NewsForm) form;// TODO Auto-generated method stub
		int total = this.newsBusiness.getTotalCount();
		int offset = 0;
		int pagesize = 10;
		try {
			offset = Integer.parseInt(request.getParameter("pager.offset"));
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			
		}
		List newslist = newsBusiness.getAllNews(offset, pagesize);
		PagerModel pm = new PagerModel();
		pm.setTotal(total);
		pm.setOffset(offset);
		pm.setList(newslist);
		request.setAttribute("pm", pm);
		return mapping.findForward("showall");
	}
	public ActionForward getOne(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		NewsForm newsForm = (NewsForm) form;// TODO Auto-generated method stub
		String id = newsForm.getId();
		News news = this.newsBusiness.getNewsByID(id);
		request.setAttribute("news", news);
		return mapping.findForward("showone");
	}
	
	public void setNewsBusiness(INewsBusiness newsBusiness) {
		this.newsBusiness = newsBusiness;
	}
}